name: build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [ linux.amd64, linux.arm64, linux.arm, windows.amd64 ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: build
        env:
          target: ${{ matrix.target }}
        run: |
          os=$(echo $target | awk -F. '{print $1}')
          arch=$(echo $target | awk -F. '{print $2}')
          ./build.sh $os $arch
