name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: get-version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build rtty release
        run: |
          COMPRESS=1 ./build.sh linux amd64
          COMPRESS=1 ./build.sh linux arm64
          COMPRESS=1 ./build.sh linux arm
          COMPRESS=1 ./build.sh windows amd64

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rtty-${{ steps.get-version.outputs.version }}-linux-amd64.tar.bz2
            rtty-${{ steps.get-version.outputs.version }}-linux-arm64.tar.bz2
            rtty-${{ steps.get-version.outputs.version }}-linux-arm.tar.bz2
            rtty-${{ steps.get-version.outputs.version }}-windows-amd64.tar.bz2
          draft: true
